[workspace]
members = [
    "crates/parse",
    "crates/cli",
    "crates/data",
    "crates/util",
    "crates/nbtdoc",
    "crates/mcf",
    "crates/db", # Contrary to popular belief, this stands for Dinnerbone
    "crates/nbt"
]