[package]
name = "mcf-util"
version = "1.0.0"
authors = ["yurihaia"]
edition = "2018"
description = "Common utility types for mcfunction-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.104"